- id: '1581536952497'
  alias: LCD 0&1 - Time and weather
  description: ''
  trigger:
  - hours: '*'
    minutes: '*'
    platform: time_pattern
    seconds: '0'
  condition: []
  action:
  - data:
      text: '  {{ now().strftime(''%a  %d/%m  %H:%M'') }}  '
    service: lcd.print0
  - data:
      text: '{{ state_attr(''weather.can_gaudir'', ''temperature'') }}C {{ state_attr(''weather.can_gaudir'',''humidity'')
        }}% {{ states(''sensor.indoor_temperature'') }}C {{ states(''sensor.indoor_humidity'').split(''.'')[0]
        }}%'
    service: lcd.print1
  mode: single
- id: '1581541286811'
  alias: Button - Spotify Play/pause
  description: ''
  trigger:
  - payload: '5'
    platform: mqtt
    topic: domos/bedroom/multiple-switch
  - payload: '1'
    platform: mqtt
    topic: domos/desk/button
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.desk1
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.bed5
  condition: []
  action:
  - data:
      payload: play
      topic: domos/media/spotify
    service: mqtt.publish
  mode: single
- id: '1581541286812'
  alias: Button  - Spotify Previous
  description: ''
  trigger:
  - payload: '4'
    platform: mqtt
    topic: domos/bedroom/multiple-switch
  - payload: '0'
    platform: mqtt
    topic: domos/desk/button
  - platform: state
    entity_id: binary_sensor.desk0
    from: 'off'
    to: 'on'
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.bed4
  condition: []
  action:
  - data:
      payload: previous
      topic: domos/media/spotify
    service: mqtt.publish
  mode: single
- id: '1581541286813'
  alias: Button  - Spotify Next
  description: ''
  trigger:
  - payload: '6'
    platform: mqtt
    topic: domos/bedroom/multiple-switch
  - payload: '2'
    platform: mqtt
    topic: domos/desk/button
  - platform: state
    entity_id: binary_sensor.desk2
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.bed6
    from: 'off'
    to: 'on'
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.bed6
  condition: []
  action:
  - data:
      payload: next
      topic: domos/media/spotify
    service: mqtt.publish
  mode: single
- id: '1581542900662'
  alias: Button - Lights off
  description: ''
  trigger:
  - payload: '11'
    platform: mqtt
    topic: domos/bedroom/multiple-switch
  - payload: '3'
    platform: mqtt
    topic: domos/desk/button
  - platform: state
    entity_id: binary_sensor.desk3
    from: 'off'
    to: 'on'
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.bed11
  condition: []
  action:
  - scene: scene.lights_off
  mode: single
- id: '1581544120342'
  alias: Button - Yeelight NORMAL
  description: ''
  trigger:
  - payload: '0'
    platform: mqtt
    topic: domos/bedroom/multiple-switch
  - payload: '4'
    platform: mqtt
    topic: domos/desk/button
  - platform: state
    entity_id: binary_sensor.desk4
    from: 'off'
    to: 'on'
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.bed0
  condition: []
  action:
  - scene: scene.day_light
  mode: single
- id: '1581544196322'
  alias: Button - Yeelight RED
  description: ''
  trigger:
  - payload: '10'
    platform: mqtt
    topic: domos/bedroom/multiple-switch
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.bed10
  condition: []
  action:
  - scene: scene.night_light
  mode: single
- id: '1582495379885'
  alias: Button - LCD backlight
  description: ''
  trigger:
  - payload: '6'
    platform: mqtt
    topic: domos/desk/button
  - payload: '1'
    platform: mqtt
    topic: domos/arduino/button
  condition: []
  action:
  - service: lcd.backlight_toggle
- id: '1582577967557'
  alias: smbc
  description: Send updated smbc via telegram
  trigger:
  - entity_id: cron.smbc_image
    from: '*'
    platform: state
    to: '*'
  condition: []
  action:
  - data:
      caption: '{{ states("cron.smbc_title") }}'
      url: '{{ states("cron.smbc_image") }}'
    service: telegram_bot.send_photo
  mode: single
- id: '1582578412319'
  alias: cron
  description: ''
  trigger:
  - hours: '*'
    minutes: '0'
    platform: time_pattern
    seconds: '0'
  condition: []
  action:
  - service: cron.update_smbc
  - service: cron.update_ara
  mode: single
- id: '1582743767819'
  alias: 'LCD 3 - Octoprint '
  description: ''
  trigger:
  - entity_id: sensor.octoprint_job_percentage
    from: '*'
    platform: state
    to: '*'
  - entity_id: sensor.octoprint_time_remaining
    for: '*'
    from: '*'
    platform: state
    to: '*'
  condition: []
  action:
  - data:
      text: 'Print: {{ states("sensor.octoprint_job_percentage").split(".")[0] }}%
        - {{ states("sensor.octoprint_time_remaining") | int | timestamp_custom("%H:%M",
        0) }}'
    service: lcd.print3
- id: '1582747396071'
  alias: ara
  description: ''
  trigger:
  - entity_id: cron.ara_article
    from: '*'
    platform: state
    to: '*'
  condition: []
  action:
  - data:
      url: '{{ state_attr("cron.ara_article", "image") }}'
    service: telegram_bot.send_photo
  - data:
      message: '{{ state_attr("cron.ara_article", "text") }}'
    service: telegram_bot.send_message
- id: '1583524050606'
  alias: Cine mode
  description: ''
  trigger:
  - entity_id: media_player.chromechastity
    from: 'off'
    platform: state
    to: '*'
  - entity_id: media_player.chromechastity
    from: '*'
    platform: state
    to: playing
  condition: []
  action:
  - entity_id: light.bedroom_yeelight
    service: light.turn_off
- id: '1583524327623'
  alias: Button - Desk Toggle
  description: ''
  trigger:
  - payload: '1'
    platform: mqtt
    topic: domos/bedroom/multiple-switch
  - payload: '0'
    platform: mqtt
    topic: domos/arduino/button
  - platform: state
    entity_id: binary_sensor.bed1
    from: 'off'
    to: 'on'
  condition: []
  action:
  - entity_id: switch.desk
    service: switch.toggle
  mode: single
- id: '1583530624338'
  alias: LCD 2 - Spotify
  description: ''
  trigger:
  - entity_id: media_player.spotify_jaume_serrats9
    from: '*'
    platform: state
    to: playing
  condition: []
  action:
  - data:
      text: '{{ state_attr("media_player.spotify_jaume_serrats9", "media_title") }}'
    service: lcd.print3
- id: '1584559888212'
  alias: Bedroom Light switch
  description: ''
  trigger:
  - payload: '3'
    platform: mqtt
    topic: domos/arduino/button
  condition: []
  action:
  - entity_id: light.bedroom_yeelight
    service: light.toggle
- id: '1584735448131'
  alias: Printer finished
  description: ''
  trigger:
  - entity_id: sensor.octoprint_time_remaining
    from: '*'
    platform: state
    to: '0'
  condition: []
  action:
  - delay: 00:00:05
  - service: script.1584734470207
  - data:
      text: ''
    service: lcd.print3
- id: '1584909339601'
  alias: Button - Mood light
  description: ''
  trigger:
  - payload: '9'
    platform: mqtt
    topic: domos/bedroom/multiple-switch
  - payload: '5'
    platform: mqtt
    topic: domos/desk/button
  - platform: state
    entity_id: binary_sensor.desk5
    from: 'off'
    to: 'on'
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.bed9
  condition: []
  action:
  - scene: scene.mood_light
  mode: single
- id: '1585763463374'
  alias: Media control bedside
  description: ''
  trigger:
  - payload: '8'
    platform: mqtt
    topic: domos/bedroom/multiple-switch
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.bed8
  condition: []
  action:
  - entity_id: media_player.chromechastity
    service: media_player.media_play_pause
- id: '1586007651403'
  alias: prank
  description: ''
  trigger:
  - entity_id: media_player.chromecast0733
    from: '*'
    platform: state
    to: '*'
  condition:
  - condition: template
    value_template: '{{ state_attr(''media_player.chromecast0733'',''media_content_id'')
      == "TUF3C3q0R-0" }}'
  action:
  - data:
      media_content_id: https://www.youtube.com/watch?v=9tUk8eZBuKY
      media_content_type: video/youtube
    entity_id: media_player.chromecast0733
    service: media_extractor.play_media
- id: '1592843603849'
  alias: Button - Ventilador
  description: ''
  trigger:
  - payload: '7'
    platform: mqtt
    topic: domos/desk/button
  - payload: '3'
    platform: mqtt
    topic: domos/bedroom/multiple-switch
  - platform: state
    entity_id: binary_sensor.bed3
    from: 'off'
    to: 'on'
  condition: []
  action:
  - entity_id: switch.power_switch_0
    service: switch.toggle
  mode: single
