- id: '1581536952497'
  alias: LCD 0&1 - Time and weather
  description: ''
  trigger:
  - hours: '*'
    minutes: '*'
    platform: time_pattern
    seconds: '0'
  condition: []
  action:
  - data:
      text: '  {{ now().strftime(''%a  %d/%m  %H:%M'') }}  '
    service: lcd.print0
  - data:
      text: '{{ state_attr(''weather.home'', ''temperature'') }}C {{ state_attr(''weather.home'',''humidity'')
        }}% {{ states(''sensor.indoor_temperature'') }}C {{ states(''sensor.indoor_humidity'').split(''.'')[0]
        }}%'
    service: lcd.print1
- id: '1581541286811'
  alias: Button 1 - Spotify Play/pause
  description: ''
  trigger:
  - payload: '1'
    platform: mqtt
    topic: domos/arduino/info/button
  condition: []
  action:
  - data: {}
    entity_id: media_player.spotify_jaume_serrats9
    service: media_player.media_play_pause
- id: '1581541286812'
  alias: Button 0 - Spotify Previous
  description: ''
  trigger:
  - payload: '0'
    platform: mqtt
    topic: domos/arduino/info/button
  condition: []
  action:
  - data: {}
    entity_id: media_player.spotify_jaume_serrats9
    service: media_player.media_previous_track
- id: '1581541286813'
  alias: Button 2 - Spotify Next
  description: ''
  trigger:
  - payload: '2'
    platform: mqtt
    topic: domos/arduino/info/button
  condition: []
  action:
  - data: {}
    entity_id: media_player.spotify_jaume_serrats9
    service: media_player.media_next_track
- id: '1581542900662'
  alias: Button 5 - Yeelight Toggle
  description: ''
  trigger:
  - payload: '5'
    platform: mqtt
    topic: domos/arduino/info/button
  condition: []
  action:
  - data: {}
    entity_id: light.bedroom_yeelight
    service: light.toggle
- id: '1581544120342'
  alias: Button 6 - Yeelight NORMAL
  description: ''
  trigger:
  - payload: '6'
    platform: mqtt
    topic: domos/arduino/info/button
  condition: []
  action:
  - scene: scene.day_light
- id: '1581544196322'
  alias: Button 7 - Yeelight RED
  description: ''
  trigger:
  - payload: '7'
    platform: mqtt
    topic: domos/arduino/info/button
  condition: []
  action:
  - scene: scene.room
- id: '1582495379885'
  alias: Button 3 - LCD backlight
  description: ''
  trigger:
  - payload: '3'
    platform: mqtt
    topic: domos/arduino/info/button
  condition: []
  action:
  - service: lcd.backlight_toggle
- id: '1582577967557'
  alias: smbc
  description: Send updatet smbc via telegram
  trigger:
  - entity_id: cron.smbc_image
    from: '*'
    platform: state
    to: '*'
  condition: []
  action:
  - data:
      caption: '{{ states("cron.smbc_title") }}'
      url: '{{ states("cron.smbc_image") }}'
    service: telegram_bot.send_photo
- id: '1582578412319'
  alias: cron
  description: ''
  trigger:
  - hours: '*'
    minutes: '0'
    platform: time_pattern
    seconds: '0'
  condition: []
  action:
  - service: cron.update_smbc
  - service: cron.update_ara
- id: '1582743767819'
  alias: 'LCD 3 - Octoprint '
  description: ''
  trigger:
  - entity_id: sensor.octoprint_job_percentage
    from: '*'
    platform: state
    to: '*'
  - entity_id: sensor.octoprint_time_remaining
    for: '*'
    from: '*'
    platform: state
    to: '*'
  condition: []
  action:
  - data:
      text: 'Print: {{ states("sensor.octoprint_job_percentage").split(".")[0] }}%
        - {{ states("sensor.octoprint_time_remaining") | int | timestamp_custom("%H:%M",
        0) }}'
    service: lcd.print3
- id: '1582747396071'
  alias: ara
  description: ''
  trigger:
  - entity_id: cron.ara_article
    from: '*'
    platform: state
    to: '*'
  condition: []
  action:
  - data:
      url: '{{ state_attr("cron.ara_article", "image") }}'
    service: telegram_bot.send_photo
  - data:
      message: '{{ state_attr("cron.ara_article", "text") }}'
    service: telegram_bot.send_message
- id: '1583524050606'
  alias: Cine mode
  description: ''
  trigger:
  - entity_id: media_player.chromechastity
    from: 'off'
    platform: state
    to: '*'
  - entity_id: media_player.chromechastity
    from: '*'
    platform: state
    to: playing
  condition: []
  action:
  - entity_id: light.bedroom_yeelight
    service: light.turn_off
- id: '1583524327623'
  alias: Button 4 - Desk Toggle
  description: ''
  trigger:
  - payload: '4'
    platform: mqtt
    topic: domos/arduino/info/button
  condition: []
  action:
  - entity_id: switch.desk
    service: switch.toggle
- id: '1583530624338'
  alias: LCD 2 - Spotify
  description: ''
  trigger:
  - entity_id: media_player.spotify_jaume_serrats9
    from: '*'
    platform: state
    to: playing
  condition: []
  action:
  - data:
      text: '{{ state_attr("media_player.spotify_jaume_serrats9", "media_title") }}'
    service: lcd.print3
- id: '1584559888212'
  alias: test
  description: ''
  trigger:
  - platform: mqtt
    topic: domos/bedroom/switch
  condition: []
  action:
  - entity_id: light.bedroom_yeelight
    service: light.toggle
