
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: raspberry.lan:8123

pi_hole:
  - host: 10.0.1.1

yeelight:
  devices:
    10.0.5.5:
      name: Bedroom yeelight

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

buttons:
indoor_meteo:
lcd:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
