
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: raspberry.lan:8123

pi_hole:
  - host: 10.0.1.1

yeelight:
  devices:
    10.0.5.5:
      name: Bedroom yeelight

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

buttons:
indoor_meteo:
lcd:
cron:

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id
notify:
  - name: Telegram notification
    platform: telegram
    chat_id: !secret telegram_chat_id
    
# Text to speech
tts:
  - platform: google_translate

switch:
  - platform: template
    switches:
      backlight:
        friendly_name: LCD Backlight
        value_template: "{{ is_state('lcd.backlight', 'on') }}"
        turn_on:
          service: lcd.backlight_on
        turn_off:
          service: lcd.backlight_off
  - platform: mqtt
    name: "Power Switch 0"
    command_topic: "domos/arduino/power/0"
    state_topic: "domos/arduino/power/0"
    payload_on: "on"
    payload_off: "off"
    state_on: "on"
    state_off: "off"
    qos: 0
    retain: true
  - platform: mqtt
    name: "Power Switch 1"
    command_topic: "domos/arduino/power/1"
    state_topic: "domos/arduino/power/1"
    payload_on: "on"
    payload_off: "off"
    state_on: "on"
    state_off: "off"
    qos: 0
    retain: true

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
homeassistant:
  customize: !include customize.yaml