
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: raspberry.lan:8123

pi_hole:
  - host: 10.0.1.1

yeelight:
  devices:
    10.0.5.5:
      name: Bedroom yeelight

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

media_player:
  - platform: mpd
    host: 10.0.5.7
    name: Nibbler Mopidy

buttons:
lcd:
cron:

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id
notify:
  - name: Telegram notification
    platform: telegram
    chat_id: !secret telegram_chat_id

octoprint:
  host: 10.0.5.3
  api_key: !secret octoprint_api_key
  bed: true

camera:
  - platform: generic
    name: Octopi Camera
    stream_source: http://10.0.5.3/webcam/?action=stream
    still_image_url: http://10.0.5.3:8080/?action=snapshot

# Text to speech
tts:
  - platform: google_translate

sensor:
  - platform: mqtt
    state_topic: "domos/arduino/info/meteo"
    name: "Indoor temperature"
    value_template: '{{ "{:2.1f}".format(float(value_json.temperature)) }}'
    unit_of_measurement: '°C'
  - platform: mqtt
    state_topic: "domos/arduino/info/meteo"
    name: "Indoor humidity"
    value_template: '{{ "{:2.1f}".format(float(value_json.humidity)) }}'
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: "domos/arduino/info/meteo"
    name: "Indoor pressure"
    value_template: '{{ "{:2.1f}".format(float(value_json.pressure)) }}'
    unit_of_measurement: 'hPa'
  - platform: mqtt
    state_topic: "domos/arduino/info/button"
    name: "Last button pressed"
  - platform: github
    access_token: !secret github_access_token
    repositories:
      - path: 'jserrats/notes'
  - platform: template
    sensors:
      outdoor_temp:
        friendly_name: "Outdoor temperature"
        unit_of_measurement: °C
        value_template: '{{ state_attr("weather.home","temperature") }}'
      outdoor_hum:
        friendly_name: "Outdoor humidity"
        unit_of_measurement: '%'
        value_template: '{{ state_attr("weather.home","humidity") }}'
      outdoor_pressure:
        friendly_name: "Outdoor pressure"
        unit_of_measurement: 'hPa'
        value_template: '{{ state_attr("weather.home","pressure") }}'

switch:
  - platform: template
    switches:
      backlight:
        friendly_name: LCD Backlight
        value_template: "{{ is_state('lcd.backlight', 'on') }}"
        turn_on:
          service: lcd.backlight_on
        turn_off:
          service: lcd.backlight_off
      desk:
        friendly_name: Desk
        value_template: '{{ is_state("binary_sensor.nibbler","on") or is_state("binary_sensor.octane","on") }}'
        turn_on:
          service: script.1583058928601
        turn_off:
          service: script.1583057164355
    
  - platform: mqtt
    name: "Power Switch 0"
    command_topic: "domos/arduino/power/0"
    state_topic: "domos/arduino/power/0"
    payload_on: "on"
    payload_off: "off"
    state_on: "on"
    state_off: "off"
    qos: 0
    retain: true
  - platform: mqtt
    name: "Power Switch 1"
    command_topic: "domos/arduino/power/1"
    state_topic: "domos/arduino/power/1"
    payload_on: "on"
    payload_off: "off"
    state_on: "on"
    state_off: "off"
    qos: 0
    retain: true
  - platform: mqtt
    name: "Ambient light"
    command_topic: "domos/arduino/pin/0"
    state_topic: "domos/arduino/pin/0"
    payload_on: "on"
    payload_off: "off"
    state_on: "on"
    state_off: "off"
    qos: 0
    retain: true
  - platform: wake_on_lan
    mac: "b4:2e:99:16:4d:7c"
    name: "Octane WoL"
    host: "10.0.5.10"
    turn_off:
      service: shell_command.octane_off
  - platform: wake_on_lan
    mac: "84:39:be:17:02:21"
    name: "Nibbler WoL"
    host: "10.0.5.7"
    turn_off:
      service: shell_command.nibbler_off
shell_command:
  octane_off: 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /config/id_rsa_ha jaume@10.0.5.10 shutdown /h /f'
  nibbler_off: 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /config/id_rsa_ha jaume@10.0.5.7 sudo poweroff'

binary_sensor:
  - platform: ping
    host: 10.0.5.10
    name: Octane
  - platform: ping
    host: 10.0.5.6
    name: Oneplus Jaume
  - platform: ping
    host: 10.0.5.7
    name: Nibbler

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml